### ISSUE TITLE
Possible bug with initial data of 0

### ISSUE THREAD

**Issue by aviculturist** [fungible-systems/jotai-query-toolkit#11]
I may have discovered a bug with handling of a query that returns a value of 0. To reproduce in the `bird-count` repo, edit `src/pages/index.tsx` and change the return value to `return 0;` within the first `getQueries`.

```
error - Error: [Jotai Query Toolkit] no initial data found for ["[\"bird-count\"]"]
    at /Projects/bird-count/node_modules/jotai-query-toolkit/nextjs.js:290:23
    at Array.map (<anonymous>)
    at useQueryInitialValues (/Projects/bird-count/node_modules/jotai-query-toolkit/nextjs.js:288:25)
    at Wrapper (/Projects/bird-count/node_modules/jotai-query-toolkit/nextjs.js:435:26)
    at processChild (/Projects/bird-count/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Projects/bird-count/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Projects/bird-count/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Projects/bird-count/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Projects/bird-count/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (/Projects/bird-count/node_modules/next/dist/server/render.js:596:45) {
  page: '/'
}
```

**Comment by aulneau** [comment]
should be fixed!
